### ISSUE TITLE
Error: “pairedData” is not a defined class

### ISSUE THREAD

**Issue by amab424** [slzhao/MultiRankSeq#1]
I get the following error when I run MultiRankSeq for paired samples:

> data(exampleCounts)
> data(exampleCountsDiff)
> result<-MultiRankSeqReport(output="MultiRankSeq1.html",diffResult=exampleCountsDiff,rawCounts=exampleCounts)
> [1] "The MultiRankSeq report was generated in C:/Users/basudana/Box Sync/R/OvaMetsProject/MultiRankSeq/MultiRankSeq1.html"
> ## Not run:
> # An example: from counts data to report, paired data
> # this code may take two minutes, because performing baySeq, DESeq2, and edgeR may be slow.
> 
> result<-MultiRankSeqReport(output="MultiRankSeq2.html",rawCounts=exampleCounts,group=c(0,0,0,1,1,1),paired=c(1:3,1:3) )
> converting counts to integer mode
> estimating size factors
> estimating dispersions
> gene-wise dispersion estimates
> mean-dispersion relationship
> final dispersion estimates
> fitting model and testing
> Error in getClass(Class, where = topenv(parent.frame())) : 
>   “pairedData” is not a defined class

Can you please help me with that?

thanks

**Comment by slzhao** [comment]
Hello,

The error was due to the changes in baySeq package. But I can't understand
its new document for paired data analysis. I've wrote a email to them and
will change it once I get their reply.

Best,
Shilin

2016-04-19 12:22 GMT-05:00 amab424 notifications@github.com:

**Comment by amab424** [comment]
If you look at section 2 of the vignette at http://bioconductor.org/packages/devel/bioc/vignettes/baySeq/inst/doc/baySeq_generic.pdf you will find the current procedure for paired data analysis, which is to construct a countData object with a three-dimensional data structure; e.g.

pairCD <- new("countData", data = array(c(pairData[,1:4], pairData[,5:8]), dim = c(nrow(pairData), 4, 2)), replicates = c(1,1,2,2), groups = list(NDE = c(1,1,1,1), DE = c(1,1,2,2)), densityFunction = bbDensity)

Do you think you can update your R code base on that?

Thanks,
Ahmed

**Comment by slzhao** [comment]
Yes. That's where I got confused. It is an example of 4 samples so it
sets replicates
= c(1,1,2,2). How can I wrote it if I have 5 samples?

2016-04-20 9:40 GMT-05:00 amab424 notifications@github.com:

**Comment by amab424** [comment]
I'm assuming you since have paired samples you will only have even numbers like 4,6,8,..

**Comment by slzhao** [comment]
For example, I have a dataset with 5 patients. They were treated by drug1
and drug2.
The 1-5 columns are: Patient1Drug1 Patient2Drug1 Patient3Drug1
Patient4Drug1 Patient5Drug1.
The 6-10 columns are: Patient1Drug2 Patient2Drug2 Patient3Drug2
Patient4Drug2 Patient5Drug2.

So this is a paired data, drug 1 and drug 2 are two groups, and each
patient is a pair in drug 1 and drug 2.

How should I write replicates and DE?

2016-04-20 16:22 GMT-05:00 amab424 notifications@github.com:

**Comment by slzhao** [comment]
Got reply from baySeq author and just updated the package. Would you please
try it again? Thanks!

2016-04-20 16:31 GMT-05:00 zhao shilin zhaoshilin@gmail.com:

**Comment by amab424** [comment]
Hi Shilin,

the code runs to the end but there are errors in the outputs:
in the csv file: "1-Likelihood(baySeq)" and "AdjLikelihood(baySeq)" columns are 'NA' for all rows.
Also, the Volcano plot for baySeq is not produced and gives the error: ## Error in plot.window(...): need finite 'ylim' values
As you would expect based on that, Venn plots don't make sense.

Thanks,

Ahmed

**Comment by slzhao** [comment]
It works in my R. Here is the sessionInfo in my R, would you please compare
with yours? I think it may related with the version of baySeq package.

## R version 3.2.3 (2015-12-10)

## Platform: x86_64-w64-mingw32/x64 (64-bit)

## Running under: Windows 7 x64 (build 7601) Service Pack 1

##

## locale:

## [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United

States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C
                      LC_TIME=English_United States.1252
##

## attached base packages:

## [1] grid      parallel  stats4    stats     graphics  grDevices

utils     datasets  methods   base
##

## other attached packages:

## [1] MultiRankSeq_1.2.6         knitr_1.12.3

VennDiagram_1.6.17         futile.logger_1.4.1        baySeq_2.4.1
          perm_1.0-0.0               abind_1.4-3

## [8] edgeR_3.12.1               limma_3.26.9

DESeq2_1.10.1              RcppArmadillo_0.6.700.3.0  Rcpp_0.12.4
          SummarizedExperiment_1.0.2 Biobase_2.30.0

## [15] GenomicRanges_1.22.4       GenomeInfoDb_1.6.3

IRanges_2.4.8              S4Vectors_0.8.11
BiocGenerics_0.16.1        devtools_1.10.0
##

## loaded via a namespace (and not attached):

## [1] genefilter_1.52.1    locfit_1.5-9.1       splines_3.2.3

lattice_0.20-33      colorspace_1.2-6     survival_2.38-3
XML_3.98-1.4         foreign_0.8-66       withr_1.0.1

## [10] DBI_0.3.1            BiocParallel_1.4.3   RColorBrewer_1.1-2

lambda.r_1.1.7       plyr_1.8.3           stringr_1.0.0
zlibbioc_1.16.0      munsell_0.4.3        gtable_0.2.0

## [19] evaluate_0.8.3       memoise_1.0.0        latticeExtra_0.6-28

geneplotter_1.48.0   curl_0.9.6           AnnotationDbi_1.32.3
highr_0.5.1          acepack_1.3-3.3      xtable_1.8-2

## [28] formatR_1.3          scales_0.4.0         Hmisc_3.17-3

annotate_1.48.0      XVector_0.10.0       gridExtra_2.2.1
ggplot2_2.1.0        digest_0.6.9         stringi_1.0-1

## [37] tools_3.2.3          magrittr_1.5         RSQLite_1.0.0

Formula_1.2-1        cluster_2.0.3        futile.options_1.0.0
httr_1.1.0           R6_2.1.2             rpart_4.1-10

## [46] nnet_7.3-12          git2r_0.14.0

2016-04-21 13:09 GMT-05:00 amab424 notifications@github.com:

**Comment by amab424** [comment]
The code doesn't give me error. I see errors in the CSV file and plots produced. Here's my session info:

> sessionInfo()
> R version 3.2.3 (2015-12-10)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
 [1] grid      parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] corrplot_0.76              ggplot2_2.1.0              reshape_0.8.5              MultiRankSeq_1.2.6         knitr_1.12.3  
 [6] VennDiagram_1.6.17         futile.logger_1.4.1        baySeq_2.5.5               perm_1.0-0.0               abind_1.4-3  
[11] DESeq2_1.10.1              RcppArmadillo_0.6.700.3.0  Rcpp_0.12.4                SummarizedExperiment_1.0.2 Biobase_2.30.0  
[16] GenomicRanges_1.22.4       GenomeInfoDb_1.6.3         IRanges_2.4.8              S4Vectors_0.8.11           BiocGenerics_0.16.1  
[21] edgeR_3.12.1               limma_3.26.9               devtools_1.11.0           

loaded via a namespace (and not attached):
 [1] locfit_1.5-9.1       lattice_0.20-33      digest_0.6.9         R6_2.1.2             plyr_1.8.3           futile.options_1.0.0 acepack_1.3-3.3  
 [8] RSQLite_1.0.0        evaluate_0.8.3       httr_1.1.0           highr_0.5.1          zlibbioc_1.16.0      curl_0.9.7           annotate_1.48.0  
[15] rpart_4.1-10         Matrix_1.2-5         labeling_0.3         splines_3.2.3        BiocParallel_1.4.3   geneplotter_1.48.0   stringr_1.0.0  
[22] foreign_0.8-66       munsell_0.4.3        nnet_7.3-12          gridExtra_2.2.1      Hmisc_3.17-3         XML_3.98-1.4         withr_1.0.1  
[29] xtable_1.8-2         gtable_0.2.0         DBI_0.3.1            git2r_0.14.0         magrittr_1.5         formatR_1.3          scales_0.4.0  
[36] stringi_1.0-1        XVector_0.10.0       genefilter_1.52.1    latticeExtra_0.6-28  Formula_1.2-1        lambda.r_1.1.7       RColorBrewer_1.1-2  
[43] tools_3.2.3          survival_2.39-2      AnnotationDbi_1.32.3 colorspace_1.2-6     cluster_2.0.4        memoise_1.0.0

**Comment by slzhao** [comment]
CSV file and Plot are good in my side. I think here is the issue:
baySeq_2.5.5
This is the development version and the author may changed some variable
names in it.

2016-04-21 16:36 GMT-05:00 amab424 notifications@github.com:

**Comment by amab424** [comment]
I installed the baySeq version you have (2.4.1) and repeated the analysis. I still have the same problem. here are the first few lines of the csv file. you can see the baySeq columns are always NA. DESeq and edger are ok

```
log2FoldChange(DESeq2)  pValue(DESeq2)  pAdj(DESeq2)    log2FoldChange(edgeR)   pValue(edgeR)   pAdj(edgeR) log2FoldChange(raw) 1-Likelihood(baySeq)    AdjLikelihood(baySeq)   rank(DESeq) rank(edgeR) rank(baySeq)    rankMethod1
```

ENSG00000264424 -6.172199452    2.58E-67    7.26E-63    -6.731236769    9.77E-53    4.64E-48    -6.315133031    NA  NA  1   1   32214   32216
ENSG00000133020 -6.173883395    3.75E-61    5.29E-57    -6.845168415    1.62E-51    3.86E-47    -6.377725492    NA  NA  2   2   34005   34009
ENSG00000244094 7.906201931 4.23E-52    3.98E-48    11.84553035 1.09E-37    1.73E-33    Inf NA  NA  3   3   8502    8508
ENSG00000089225 -6.489043128    9.56E-49    6.73E-45    -7.591912822    9.48E-37    1.13E-32    -7.361943774    NA  NA  4   4   24525   24533
ENSG00000197953 -5.316210994    3.77E-43    2.12E-39    -5.968441372    7.42E-26    2.21E-22    -5.436236665    NA  NA  5   16  37673   37694
ENSG00000272736 -5.500100787    1.35E-39    6.34E-36    -6.436560209    7.55E-31    3.28E-27    -5.222971236    NA  NA  6   10  3885    3901
ENSG00000182230 4.122119483 1.81E-39    7.30E-36    4.342877681 1.31E-29    4.78E-26    4.4997931   NA  NA  7   13  30760   30780

**Comment by amab424** [comment]
also, here are my paired information:
Samples: The samples labeled by 0 will be taken as reference and compared with samples labeled by 1:

## 0029-50T 0030-50T 0031-50T 0032-50T 0033-50T 0034-50T 0035-50T 0003-56M 0004-56M 0006-56M 0008-56M 0009-56M 0014-56M 0018-56M

## 0        0        0        0        0        0        0        1        1        1        1        1        1        1

Pairs (The samples labeled by the same number will be taken as a pair):

## 0029-50T 0030-50T 0031-50T 0032-50T 0033-50T 0034-50T 0035-50T 0003-56M 0004-56M 0006-56M 0008-56M 0009-56M 0014-56M 0018-56M

## 1        2        3        4        5        6        7        1        2        3        4        5        6        7

**Comment by slzhao** [comment]
Updated a new version. Tested it with following code and it worked.
Please let me know if it works for you.

set.seed(123)
count<-matrix(sample(1:1000,4200,replace = TRUE),ncol=14)
row.names(count)<-paste0("Gene",1:300)
colnames(count)<-paste0("Sample",1:14)
head(count)
library(MultiRankSeq)
group=rep(c(0,1),each=7)
paired=rep(1:7,2)
result<-MultiRankSeqReport(output="MultiRankSeq3.html",rawCounts=count,group=group,paired=paired)

2016-04-21 17:18 GMT-05:00 amab424 notifications@github.com:

**Comment by amab424** [comment]
Thank you. I think it woks well this time. The only thing that looks weird is the Venn plot for "log2 fold change=>1". It looks weird in both my data and the example you sent.
Ahmed
Date: Thu, 21 Apr 2016 23:58:39 -0700

**Comment by slzhao** [comment]
Did you mean in the venn of "log2 fold change >=1", two circles were
covered by edgeR circle? It is normal as their significant genes were all
covered by significant genes from edgeR.

2016-04-22 10:41 GMT-05:00 amab424 notifications@github.com:

**Comment by amab424** [comment]
Ok then all is working well. Thank you very much for the effort to make this work. I only have one more question: is there an option within this package to compare only two packages instead of three? e.g. Deseq and edger only?

Thanks
Ahmed

**Comment by slzhao** [comment]
Good question! I am developing it but there is no option to do it at this
time.

Best,
Shilin

2016-04-22 11:06 GMT-05:00 amab424 notifications@github.com:

> Ok then all is working well. Thank you very much for the effort to make
> this work. I only have one more question: is there an option within this
> package to compare only two packages instead of three? e.g. Deseq and edger
> only?
> 
> Thanks
> Ahmed
>
